# Generated by Django 6.0.4 on 2026-04-17 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="member",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="unit",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
    ]
